
version: '3.8'

services:
  tartube:
    build: .
    container_name: tartube
    restart: unless-stopped
    
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - DARK_MODE=1
      
      # Permissions
      - USER_ID=0
      - GROUP_ID=0
      
      # Locale
      - TZ=Europe/Paris
    
    volumes:
      - ./appdata:/config:rw
      - ./downloads:/downloads:rw
    
    ports:
      - "7800:5800"  # Interface web
      - "7900:5900"  # VNC
    
    networks:
      - tartube-net

networks:
  tartube-net: